version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    image: dacontainers/daapp
    container_name: frontend
    ports:
      - "8080:8080"
    volumes:
      - appdata:/usr/local/tomcat/webapps

  web:
    restart: unless-stopped
    build: ./web
    image: dacontainers/daweb
    ports:
      - "80:80"
      - "443:443"
   
volumes:
  appdata: {}